export const packingTypes = [
  { label: 'BAG(S) ', value: '40' },
  { label: 'BALE(S) ', value: '4' },
  { label: 'BUNDLE(S) ', value: '3' },
  { label: 'BAILS ', value: '42' },
  { label: 'BOX(S) ', value: '5' },
  { label: 'BARREL(S) ', value: '1' },
  { label: 'BRIQUETTE(S) ', value: '6' },
  { label: 'CAN(S) ', value: '7' },
  { label: 'CARBOY(S) ', value: '8' },
  { label: 'CABLE DRUM(S) ', value: '9' },
  { label: 'COIL(S) ', value: '10' },
  { label: 'CRATE(S) ', value: '11' },
  { label: 'CASE(S) ', value: '12' },
  { label: 'CARTON(S) ', value: '2' },
  { label: 'CONTAINER(S) ', value: '38' },
  { label: 'CYLINDER(S) ', value: '13' },
  { label: 'DRUM(S) ', value: '14' },
  { label: 'DOZEN(S) ', value: '15' },
  { label: 'FIBRE DRUM(S) ', value: '16' },
  { label: 'ITEM(S) ', value: '17' },
  { label: 'JOTTA(S) ', value: '18' },
  { label: 'KEG(S) ', value: '19' },
  { label: 'LOOSE PACKAGE(S) ', value: '41' },
  { label: 'MODULE(S) ', value: '20' },
  { label: 'METAL DRUM(S) ', value: '21' },
  { label: 'METRIC TON(S) ', value: '22' },
  { label: 'PAIL(S) ', value: '23' },
  { label: 'PIECE(S) ', value: '24' },
  { label: 'PLASTIC DRUM(S) ', value: '25' },
  { label: 'PACKAGE(S) ', value: '26' },
  { label: 'PACKET(S) ', value: '27' },
  { label: 'PALLET(S) ', value: '39' },
  { label: 'REEL(S) ', value: '28' },
  { label: 'ROLL(S) ', value: '29' },
  { label: 'SACK(S) ', value: '30' },
  { label: 'SET(S) ', value: '31' },
  { label: 'SHEET(S) ', value: '32' },
  { label: 'SKID(S) ', value: '33' },
  { label: 'STEEL PACKAGE(S) ', value: '34' },
  { label: 'STEEL PLATE(S) ', value: '35' },
  { label: 'STEEL TRUNK(S) ', value: '36' },
  { label: 'TON(S) ', value: '37' },
  { label: 'UNITS ', value: '43' },
];

export const units = [
  { label: 'CM', value: 'cm' },
  { label: 'MM', value: 'mm' },
  { label: 'Inches', value: 'inches' },
];

export const incoTerms = [
  { label: ' CIF - Cost, Freight, and Insurance', value: '1' },
  { label: ' CFR - Cost and Freight', value: '2' },
  { label: ' FCA - Free Carrier', value: '3' },
  { label: ' EXW - Ex Works', value: '4' },
  { label: ' DAP - Delivered at Place', value: '5' },
  { label: ' DDU - ', value: '6' },
  { label: ' DDP - Delivered Duty Paid', value: '7' },
  { label: ' FOB - Free on Board', value: '8' },
  { label: ' FAS - Free Alongside Ship', value: '12' },
  { label: ' CPT - Carriage Paid To', value: '13' },
  { label: ' CIP - Carriage and Insurance Paid To', value: '14' },
  { label: ' DAT - Delivered at Terminal', value: '15' },
];
